// Copyright (c) ZeroC, Inc.

// slice2java version 3.8.0-alpha.0
// <auto-generated>Generated from Slice file 'Test.ice'.</auto-generated>

package Test;

/**
 * Helper class for marshaling/unmarshaling BDict.
 */
public final class BDictHelper {
    /**
     * Marshals a dictionary of {@code BDict} into an output stream.
     *
     * @param ostr the output stream
     * @param v the dictionary to marshal
     */
    public static void write(com.zeroc.Ice.OutputStream ostr, java.util.Map<java.lang.Integer, B> v) {
        if (v == null) {
            ostr.writeSize(0);
        } else {
            ostr.writeSize(v.size());
            for (java.util.Map.Entry<java.lang.Integer, B> e : v.entrySet()) {
                ostr.writeInt(e.getKey());
                ostr.writeValue(e.getValue());
            }
        }
    }

    /**
     * Unmarshals a dictionary of {@code BDict} from an input stream.
     *
     * @param istr the input stream
     * @return the dictionary
     */
    public static java.util.Map<java.lang.Integer, B> read(com.zeroc.Ice.InputStream istr) {
        java.util.Map<java.lang.Integer, B> v;
        v = new java.util.HashMap<java.lang.Integer, Test.B>();
        int sz0 = istr.readSize();
        for (int i0 = 0; i0 < sz0; i0++) {
            final int key;
            key = istr.readInt();
            istr.readValue(value -> v.put(key, value), B.class);
        }
        return v;
    }

    /**
     * Marshals an optional dictionary of {@code BDict} into an output stream.
     *
     * @param ostr the output stream
     * @param tag the tag
     * @param v the dictionary to marshal
     */
    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<java.util.Map<java.lang.Integer, B>> v) {
        if (v != null && v.isPresent()) {
            write(ostr, tag, v.get());
        }
    }

    /**
     * Marshals an optional dictionary of {@code BDict} into an output stream.
     *
     * @param ostr the output stream
     * @param tag the tag
     * @param v the dictionary to marshal
     */
    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Map<java.lang.Integer, B> v) {
        if (ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize)) {
            int pos = ostr.startSize();
            BDictHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    /**
     * Unmarshals an optional dictionary of {@code BDict} from an input stream.
     *
     * @param istr the input stream
     * @param tag the tag
     * @return the dictionary
     */
    public static java.util.Optional<java.util.Map<java.lang.Integer, B>> read(com.zeroc.Ice.InputStream istr, int tag) {
        if (istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize)) {
            istr.skip(4);
            java.util.Map<java.lang.Integer, B> v;
            v = BDictHelper.read(istr);
            return java.util.Optional.of(v);
        } else {
            return java.util.Optional.empty();
        }
    }
}
