//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.8.0-alpha.0
//
// <auto-generated>
//
// Generated from file `Test.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __Test_h__
#define __Test_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/Ice.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION  != 30850
#       error Ice version mismatch: an exact match is required for beta generated code
#   endif
#endif

#ifndef INTERCEPTOR_TEST_API
#   if defined(ICE_STATIC_LIBS)
#       define INTERCEPTOR_TEST_API /**/
#   elif defined(INTERCEPTOR_TEST_API_EXPORTS)
#       define INTERCEPTOR_TEST_API ICE_DECLSPEC_EXPORT
#   else
#       define INTERCEPTOR_TEST_API ICE_DECLSPEC_IMPORT
#   endif
#endif

namespace Test
{

class MyObject;
class MyObjectPrx;

using MyObjectPrxPtr = ::std::optional<MyObjectPrx>;

}

namespace Test
{

}

namespace Test
{

class INTERCEPTOR_TEST_API MyObjectPrx : public ::Ice::Proxy<MyObjectPrx, ::Ice::ObjectPrx>
{
public:

    int add(int x, int y, const ::Ice::Context& context = ::Ice::noExplicitContext) const;

    ::std::future<int> addAsync(int x, int y, const ::Ice::Context& context = ::Ice::noExplicitContext)const;

    ::std::function<void()>
    addAsync(int x, int y,
             ::std::function<void(int)> response,
             ::std::function<void(::std::exception_ptr)> ex = nullptr,
             ::std::function<void(bool)> sent = nullptr,
             const ::Ice::Context& context = ::Ice::noExplicitContext) const;

    /// \cond INTERNAL
    void _iceI_add(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<int>>&, int, int, const ::Ice::Context&) const;
    /// \endcond

    int addWithRetry(int x, int y, const ::Ice::Context& context = ::Ice::noExplicitContext) const;

    ::std::future<int> addWithRetryAsync(int x, int y, const ::Ice::Context& context = ::Ice::noExplicitContext)const;

    ::std::function<void()>
    addWithRetryAsync(int x, int y,
                      ::std::function<void(int)> response,
                      ::std::function<void(::std::exception_ptr)> ex = nullptr,
                      ::std::function<void(bool)> sent = nullptr,
                      const ::Ice::Context& context = ::Ice::noExplicitContext) const;

    /// \cond INTERNAL
    void _iceI_addWithRetry(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<int>>&, int, int, const ::Ice::Context&) const;
    /// \endcond

    int badAdd(int x, int y, const ::Ice::Context& context = ::Ice::noExplicitContext) const;

    ::std::future<int> badAddAsync(int x, int y, const ::Ice::Context& context = ::Ice::noExplicitContext)const;

    ::std::function<void()>
    badAddAsync(int x, int y,
                ::std::function<void(int)> response,
                ::std::function<void(::std::exception_ptr)> ex = nullptr,
                ::std::function<void(bool)> sent = nullptr,
                const ::Ice::Context& context = ::Ice::noExplicitContext) const;

    /// \cond INTERNAL
    void _iceI_badAdd(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<int>>&, int, int, const ::Ice::Context&) const;
    /// \endcond

    int notExistAdd(int x, int y, const ::Ice::Context& context = ::Ice::noExplicitContext) const;

    ::std::future<int> notExistAddAsync(int x, int y, const ::Ice::Context& context = ::Ice::noExplicitContext)const;

    ::std::function<void()>
    notExistAddAsync(int x, int y,
                     ::std::function<void(int)> response,
                     ::std::function<void(::std::exception_ptr)> ex = nullptr,
                     ::std::function<void(bool)> sent = nullptr,
                     const ::Ice::Context& context = ::Ice::noExplicitContext) const;

    /// \cond INTERNAL
    void _iceI_notExistAdd(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<int>>&, int, int, const ::Ice::Context&) const;
    /// \endcond

    int badSystemAdd(int x, int y, const ::Ice::Context& context = ::Ice::noExplicitContext) const;

    ::std::future<int> badSystemAddAsync(int x, int y, const ::Ice::Context& context = ::Ice::noExplicitContext)const;

    ::std::function<void()>
    badSystemAddAsync(int x, int y,
                      ::std::function<void(int)> response,
                      ::std::function<void(::std::exception_ptr)> ex = nullptr,
                      ::std::function<void(bool)> sent = nullptr,
                      const ::Ice::Context& context = ::Ice::noExplicitContext) const;

    /// \cond INTERNAL
    void _iceI_badSystemAdd(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<int>>&, int, int, const ::Ice::Context&) const;
    /// \endcond

    int amdAdd(int x, int y, const ::Ice::Context& context = ::Ice::noExplicitContext) const;

    ::std::future<int> amdAddAsync(int x, int y, const ::Ice::Context& context = ::Ice::noExplicitContext)const;

    ::std::function<void()>
    amdAddAsync(int x, int y,
                ::std::function<void(int)> response,
                ::std::function<void(::std::exception_ptr)> ex = nullptr,
                ::std::function<void(bool)> sent = nullptr,
                const ::Ice::Context& context = ::Ice::noExplicitContext) const;

    /// \cond INTERNAL
    void _iceI_amdAdd(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<int>>&, int, int, const ::Ice::Context&) const;
    /// \endcond

    int amdAddWithRetry(int x, int y, const ::Ice::Context& context = ::Ice::noExplicitContext) const;

    ::std::future<int> amdAddWithRetryAsync(int x, int y, const ::Ice::Context& context = ::Ice::noExplicitContext)const;

    ::std::function<void()>
    amdAddWithRetryAsync(int x, int y,
                         ::std::function<void(int)> response,
                         ::std::function<void(::std::exception_ptr)> ex = nullptr,
                         ::std::function<void(bool)> sent = nullptr,
                         const ::Ice::Context& context = ::Ice::noExplicitContext) const;

    /// \cond INTERNAL
    void _iceI_amdAddWithRetry(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<int>>&, int, int, const ::Ice::Context&) const;
    /// \endcond

    int amdBadAdd(int x, int y, const ::Ice::Context& context = ::Ice::noExplicitContext) const;

    ::std::future<int> amdBadAddAsync(int x, int y, const ::Ice::Context& context = ::Ice::noExplicitContext)const;

    ::std::function<void()>
    amdBadAddAsync(int x, int y,
                   ::std::function<void(int)> response,
                   ::std::function<void(::std::exception_ptr)> ex = nullptr,
                   ::std::function<void(bool)> sent = nullptr,
                   const ::Ice::Context& context = ::Ice::noExplicitContext) const;

    /// \cond INTERNAL
    void _iceI_amdBadAdd(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<int>>&, int, int, const ::Ice::Context&) const;
    /// \endcond

    int amdNotExistAdd(int x, int y, const ::Ice::Context& context = ::Ice::noExplicitContext) const;

    ::std::future<int> amdNotExistAddAsync(int x, int y, const ::Ice::Context& context = ::Ice::noExplicitContext)const;

    ::std::function<void()>
    amdNotExistAddAsync(int x, int y,
                        ::std::function<void(int)> response,
                        ::std::function<void(::std::exception_ptr)> ex = nullptr,
                        ::std::function<void(bool)> sent = nullptr,
                        const ::Ice::Context& context = ::Ice::noExplicitContext) const;

    /// \cond INTERNAL
    void _iceI_amdNotExistAdd(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<int>>&, int, int, const ::Ice::Context&) const;
    /// \endcond

    int amdBadSystemAdd(int x, int y, const ::Ice::Context& context = ::Ice::noExplicitContext) const;

    ::std::future<int> amdBadSystemAddAsync(int x, int y, const ::Ice::Context& context = ::Ice::noExplicitContext)const;

    ::std::function<void()>
    amdBadSystemAddAsync(int x, int y,
                         ::std::function<void(int)> response,
                         ::std::function<void(::std::exception_ptr)> ex = nullptr,
                         ::std::function<void(bool)> sent = nullptr,
                         const ::Ice::Context& context = ::Ice::noExplicitContext) const;

    /// \cond INTERNAL
    void _iceI_amdBadSystemAdd(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<int>>&, int, int, const ::Ice::Context&) const;
    /// \endcond

    /**
     * Obtains the Slice type ID of this interface.
     * @return The fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    explicit MyObjectPrx(const ::Ice::ObjectPrx& other) : ::Ice::ObjectPrx(other)
    {
    }

    MyObjectPrx(const MyObjectPrx& other) noexcept : ::Ice::ObjectPrx(other)
    {
    }

    MyObjectPrx(MyObjectPrx&& other) noexcept : ::Ice::ObjectPrx(::std::move(other))
    {
    }

    MyObjectPrx(const ::std::shared_ptr<::Ice::Communicator>& communicator, const ::std::string& proxyString) :
        ::Ice::ObjectPrx(communicator, proxyString)
    {
    }

    MyObjectPrx& operator=(const MyObjectPrx& rhs) noexcept
    {
        ::Ice::ObjectPrx::operator=(rhs);
        return *this;
    }

    MyObjectPrx& operator=(MyObjectPrx&& rhs) noexcept
    {
        ::Ice::ObjectPrx::operator=(::std::move(rhs));
        return *this;
    }

    /// \cond INTERNAL
    static MyObjectPrx _fromReference(::IceInternal::ReferencePtr ref) { return MyObjectPrx(::std::move(ref)); }

protected:

    MyObjectPrx() = default;

    explicit MyObjectPrx(::IceInternal::ReferencePtr&& ref) : ::Ice::ObjectPrx(::std::move(ref))
    {
    }
    /// \endcond
};

}

namespace Test
{

class ICE_CLASS(INTERCEPTOR_TEST_API) InvalidInputException : public ::Ice::UserExceptionHelper<InvalidInputException, ::Ice::UserException>
{
public:

    ICE_MEMBER(INTERCEPTOR_TEST_API) virtual ~InvalidInputException();

    InvalidInputException(const InvalidInputException&) = default;

    InvalidInputException() = default;

    /**
     * One-shot constructor to initialize all data members.
     */
    InvalidInputException(const ::std::string& message) :
        message(message)
    {
    }

    /**
     * Obtains a tuple containing all of the exception's data members.
     * @return The data members in a tuple.
     */
    std::tuple<const ::std::string&> ice_tuple() const
    {
        return std::tie(message);
    }

    /**
     * Obtains the Slice type ID of this exception.
     * @return The fully-scoped type ID.
     */
    ICE_MEMBER(INTERCEPTOR_TEST_API) static const ::std::string& ice_staticId();

    ::std::string message;
};

/// \cond INTERNAL
static InvalidInputException _iceS_InvalidInputException_init;
/// \endcond

}

namespace Test
{

class INTERCEPTOR_TEST_API MyObject : public virtual ::Ice::Object
{
public:

    using ProxyType = MyObjectPrx;

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    bool ice_isA(::std::string id, const ::Ice::Current& current) const override;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    ::std::vector<::std::string> ice_ids(const ::Ice::Current& current) const override;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    ::std::string ice_id(const ::Ice::Current& current) const override;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual int add(int x, int y, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_add(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual int addWithRetry(int x, int y, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_addWithRetry(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual int badAdd(int x, int y, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_badAdd(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual int notExistAdd(int x, int y, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_notExistAdd(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual int badSystemAdd(int x, int y, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_badSystemAdd(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual void amdAddAsync(int x, int y, ::std::function<void(int returnValue)> response, ::std::function<void(::std::exception_ptr)> exception, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_amdAdd(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual void amdAddWithRetryAsync(int x, int y, ::std::function<void(int returnValue)> response, ::std::function<void(::std::exception_ptr)> exception, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_amdAddWithRetry(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual void amdBadAddAsync(int x, int y, ::std::function<void(int returnValue)> response, ::std::function<void(::std::exception_ptr)> exception, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_amdBadAdd(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual void amdNotExistAddAsync(int x, int y, ::std::function<void(int returnValue)> response, ::std::function<void(::std::exception_ptr)> exception, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_amdNotExistAdd(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual void amdBadSystemAddAsync(int x, int y, ::std::function<void(int returnValue)> response, ::std::function<void(::std::exception_ptr)> exception, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_amdBadSystemAdd(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&) override;
    /// \endcond
};

}

/// \cond STREAM
namespace Ice
{

template<typename S>
struct StreamReader<::Test::InvalidInputException, S>
{
    static void read(S* istr, ::Test::InvalidInputException& v)
    {
        istr->readAll(v.message);
    }
};

}
/// \endcond

/// \cond INTERNAL
namespace Test
{

using MyObjectPtr = ::std::shared_ptr<MyObject>;

}
/// \endcond

#include <IceUtil/PopDisableWarnings.h>
#endif
