// Copyright (c) ZeroC, Inc.

// slice2java version 3.8.0-alpha.0
// <auto-generated>Generated from Slice file 'Test.ice'.</auto-generated>

package Test;

@com.zeroc.Ice.SliceTypeId(value = "::Test::BaseEx")
public class BaseEx extends com.zeroc.Ice.UserException
{
    public BaseEx()
    {
        this.reason = "";
    }

    public BaseEx(String reason)
    {
        this.reason = reason;
    }

    public String ice_id()
    {
        return "::Test::BaseEx";
    }

    public String reason;

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::Test::BaseEx", -1, true);
        ostr_.writeString(reason);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        reason = istr_.readString();
        istr_.endSlice();
    }

    /** @hidden */
    private static final long serialVersionUID = -1259541178635794051L;
}
