// Copyright (c) ZeroC, Inc.

// slice2swift version 3.8.0-alpha.0
// <auto-generated>Generated from Slice file 'Key.ice'.</auto-generated>

import Foundation
import Ice

public enum `continue`: Swift.UInt8 {
    case myFirstEnumerator = 0
    case mySecondEnumerator = 1
    public init() {
        self = .myFirstEnumerator
    }
}

/// An `Ice.InputStream` extension to read `continue` enumerated values from the stream.
public extension Ice.InputStream {
    /// Read an enumerated value.
    ///
    /// - Returns:  The enumerated value.
    func read() throws -> `continue` {
        let rawValue: Swift.UInt8 = try read(enumMaxValue: 1)
        guard let val = `continue`(rawValue: rawValue) else {
            throw Ice.MarshalException("invalid enum value")
        }
        return val
    }

    /// Read an optional enumerated value from the stream.
    ///
    /// - Parameter tag: The numeric tag associated with the value.
    ///
    /// - Returns: The enumerated value.
    func read(tag: Swift.Int32) throws -> `continue`? {
        guard try readOptional(tag: tag, expectedFormat: .Size) else {
            return nil
        }
        return try read() as `continue`
    }
}

/// An `Ice.OutputStream` extension to write `continue` enumerated values to the stream.
public extension Ice.OutputStream {
    /// Writes an enumerated value to the stream.
    ///
    /// - Parameter v: The enumerator to write.
    func write(_ v: `continue`) {
        write(enum: v.rawValue, maxValue: 1)
    }

    /// Writes an optional enumerated value to the stream.
    ///
    /// - Parameter tag: The numeric tag associated with the value.
    /// - Parameter value: The enumerator to write.
    func write(tag: Swift.Int32, value: `continue`?) {
        guard let v = value else {
            return
        }
        write(tag: tag, val: v.rawValue, maxValue: 1)
    }
}

public struct `guard`: Swift.Hashable {
    public var `default`: Swift.Int32 = 0

    public init() {}

    public init(`default`: Swift.Int32) {
        self.`default` = `default`
    }
}

/// An `Ice.InputStream` extension to read `guard` structured values from the stream.
public extension Ice.InputStream {
    /// Read a `guard` structured value from the stream.
    ///
    /// - Returns: The structured value read from the stream.
    func read() throws -> `guard` {
        var v = `guard`()
        v.`default` = try self.read()
        return v
    }

    /// Read an optional `guard?` structured value from the stream.
    ///
    /// - Parameter tag: The numeric tag associated with the value.
    ///
    /// - Returns: The structured value read from the stream.
    func read(tag: Swift.Int32) throws -> `guard`? {
        guard try readOptional(tag: tag, expectedFormat: .VSize) else {
            return nil
        }
        try skipSize()
        return try read() as `guard`
    }
}

/// An `Ice.OutputStream` extension to write `guard` structured values from the stream.
public extension Ice.OutputStream {
    /// Write a `guard` structured value to the stream.
    ///
    /// - Parameter v: The value to write to the stream.
    func write(_ v: `guard`) {
        self.write(v.`default`)
    }

    /// Write an optional `guard?` structured value to the stream.
    ///
    /// - Parameter tag: The numeric tag associated with the value.
    /// - Parameter value: The value to write to the stream.
    func write(tag: Swift.Int32, value: `guard`?) {
        if let v = value {
            if writeOptional(tag: tag, format: .VSize) {
                write(size: 4)
                write(v)
            }
        }
    }
}

/// Traits for Slice interface 'break'.
public struct breakTraits: Ice.SliceTraits {
    public static let staticIds = ["::Ice::Object", "::import::break"]
    public static let staticId = "::import::break"
}

public protocol breakPrx: Ice.ObjectPrx {}

private final class breakPrxI: Ice.ObjectPrxI, breakPrx {
    public override class func ice_staticId() -> Swift.String {
        return breakTraits.staticId
    }
}

/// Makes a new proxy from a communicator and a proxy string.
///
/// - Parameters:
///    - communicator: The communicator of the new proxy.
///    - proxyString: The proxy string to parse.
///    - type: The type of the new proxy.
///
/// - Throws: `Ice.ParseException` if the proxy string is invalid.
///
/// - Returns: A new proxy with the requested type.
public func makeProxy(communicator: Ice.Communicator, proxyString: String, type: breakPrx.Protocol) throws -> breakPrx {
    try communicator.makeProxyImpl(proxyString) as breakPrxI
}

/// Casts a proxy to the requested type. This call contacts the server and verifies that the object
/// implements this type.
///
/// It will throw a local exception if a communication error occurs. You can optionally supply a
/// facet name and a context map.
///
/// - Parameters:
///   - prx: The proxy to be cast.
///   - type: The proxy type to cast to.
///   - facet: The optional name of the desired facet.
///   - context: The optional context dictionary for the remote invocation.
///
/// - Returns: A proxy with the requested type or nil if the objet does not support this type.
///
/// - Throws: `Ice.LocalException` if a communication error occurs.
public func checkedCast(prx: Ice.ObjectPrx, type: breakPrx.Protocol, facet: Swift.String? = nil, context: Ice.Context? = nil) async throws -> breakPrx? {
    return try await breakPrxI.checkedCast(prx: prx, facet: facet, context: context) as breakPrxI?
}

/// Downcasts the given proxy to this type without contacting the remote server.
///
/// - Parameters:
///   - prx: The proxy to be cast.
///   - type: The proxy type to cast to.
///   - facet: The optional name of the desired facet.
///
/// - Returns: A proxy with the requested type.
public func uncheckedCast(prx: Ice.ObjectPrx, type: breakPrx.Protocol, facet: Swift.String? = nil) -> breakPrx {
    return breakPrxI.uncheckedCast(prx: prx, facet: facet) as breakPrxI
}

/// Returns the Slice type id of the interface associated with this proxy type.
///
/// - Parameter type:  The proxy type to retrieve the type id.
///
/// - Returns: The type id of the interface associated with this proxy type.
public func ice_staticId(_ type: breakPrx.Protocol) -> Swift.String {
    return breakTraits.staticId
}

/// Extension to `Ice.InputStream` class to support reading proxies of type
/// `breakPrx`.
public extension Ice.InputStream {
    /// Extracts a proxy from the stream. The stream must have been initialized with a communicator.
    ///
    /// - Parameter type: The type of the proxy to be extracted.
    ///
    /// - Returns: The extracted proxy.
    func read(_ type: breakPrx.Protocol) throws -> breakPrx? {
        return try read() as breakPrxI?
    }
    /// Extracts a proxy from the stream. The stream must have been initialized with a communicator.
    ///
    /// - Parameter tag:  The numeric tag associated with the value.
    /// - Parameter type: The type of the proxy to be extracted.
    ///
    /// - Returns: The extracted proxy.
    func read(tag: Swift.Int32, type: breakPrx.Protocol) throws -> breakPrx? {
        return try read(tag: tag) as breakPrxI?
    }
}

public extension breakPrx {
    func `case`(_ iceP_class: Swift.Int32, context: Ice.Context? = nil) async throws -> Swift.Int32 {
        return try await _impl._invoke(operation: "case",
                                       mode: .normal,
                                       write: { ostr in
                                           ostr.write(iceP_class)
                                       },
                                       read: { istr in
                                           let iceP_try: Swift.Int32 = try istr.read()
                                           return iceP_try
                                       },
                                       context: context)
    }
}

public extension Ice.DefaultSliceLoader {
    @objc static func resolveTypeId_import_switch() -> AnyObject.Type {
        `switch`.self
    }
}

open class `switch`: Ice.Value {
    public var `remappedExport`: breakPrx? = nil
    public var remappedVolatile: Swift.Int32 = 0

    public required init() {}

    public init(`remappedExport`: breakPrx?, remappedVolatile: Swift.Int32) {
        self.`remappedExport` = `remappedExport`
        self.remappedVolatile = remappedVolatile
    }

    /// - Returns: The Slice type ID of the interface supported by this object.
    open override class func ice_staticId() -> Swift.String { "::import::switch" }

    open override func _iceReadImpl(from istr: Ice.InputStream) throws {
        _ = try istr.startSlice()
        self.`remappedExport` = try istr.read(breakPrx.self)
        self.remappedVolatile = try istr.read()
        try istr.endSlice()
    }

    open override func _iceWriteImpl(to ostr: Ice.OutputStream) {
        ostr.startSlice(typeId: `switch`.ice_staticId(), compactId: -1, last: true)
        ostr.write(self.`remappedExport`)
        ostr.write(self.remappedVolatile)
        ostr.endSlice()
    }
}

public extension Ice.DefaultSliceLoader {
    @objc static func resolveTypeId_import_return() -> AnyObject.Type {
        `return`.self
    }
}

open class `return`: Ice.UserException, @unchecked Sendable {
    public var Int32: Swift.Int32 = 0

    public required init() {}

    public init(Int32: Swift.Int32) {
        self.Int32 = Int32
    }

    /// - Returns: The Slice type ID of this exception.
    open override class func ice_staticId() -> Swift.String { "::import::return" }

    open override func _iceWriteImpl(to ostr: Ice.OutputStream) {
        ostr.startSlice(typeId: `return`.ice_staticId(), compactId: -1, last: true)
        ostr.write(self.Int32)
        ostr.endSlice()
    }

    open override func _iceReadImpl(from istr: Ice.InputStream) throws {
        _ = try istr.startSlice()
        self.Int32 = try istr.read()
        try istr.endSlice()
    }
}

public extension Ice.DefaultSliceLoader {
    @objc static func resolveTypeId_import_as() -> AnyObject.Type {
        `as`.self
    }
}

open class `as`: `return`, @unchecked Sendable {
    public var `switch`: Swift.Int32 = 0

    public required init() {
        super.init()
    }

    public init(Int32: Swift.Int32, `switch`: Swift.Int32) {
        self.`switch` = `switch`
        super.init(Int32: Int32)
    }

    /// - Returns: The Slice type ID of this exception.
    open override class func ice_staticId() -> Swift.String { "::import::as" }

    open override func _iceWriteImpl(to ostr: Ice.OutputStream) {
        ostr.startSlice(typeId: `as`.ice_staticId(), compactId: -1, last: false)
        ostr.write(self.`switch`)
        ostr.endSlice()
        super._iceWriteImpl(to: ostr);
    }

    open override func _iceReadImpl(from istr: Ice.InputStream) throws {
        _ = try istr.startSlice()
        self.`switch` = try istr.read()
        try istr.endSlice()
        try super._iceReadImpl(from: istr);
    }
}

/// Traits for Slice interface 'do'.
public struct doTraits: Ice.SliceTraits {
    public static let staticIds = ["::Ice::Object", "::import::break", "::import::do"]
    public static let staticId = "::import::do"
}

public protocol doPrx: breakPrx {}

private final class doPrxI: Ice.ObjectPrxI, doPrx {
    public override class func ice_staticId() -> Swift.String {
        return doTraits.staticId
    }
}

/// Makes a new proxy from a communicator and a proxy string.
///
/// - Parameters:
///    - communicator: The communicator of the new proxy.
///    - proxyString: The proxy string to parse.
///    - type: The type of the new proxy.
///
/// - Throws: `Ice.ParseException` if the proxy string is invalid.
///
/// - Returns: A new proxy with the requested type.
public func makeProxy(communicator: Ice.Communicator, proxyString: String, type: doPrx.Protocol) throws -> doPrx {
    try communicator.makeProxyImpl(proxyString) as doPrxI
}

/// Casts a proxy to the requested type. This call contacts the server and verifies that the object
/// implements this type.
///
/// It will throw a local exception if a communication error occurs. You can optionally supply a
/// facet name and a context map.
///
/// - Parameters:
///   - prx: The proxy to be cast.
///   - type: The proxy type to cast to.
///   - facet: The optional name of the desired facet.
///   - context: The optional context dictionary for the remote invocation.
///
/// - Returns: A proxy with the requested type or nil if the objet does not support this type.
///
/// - Throws: `Ice.LocalException` if a communication error occurs.
public func checkedCast(prx: Ice.ObjectPrx, type: doPrx.Protocol, facet: Swift.String? = nil, context: Ice.Context? = nil) async throws -> doPrx? {
    return try await doPrxI.checkedCast(prx: prx, facet: facet, context: context) as doPrxI?
}

/// Downcasts the given proxy to this type without contacting the remote server.
///
/// - Parameters:
///   - prx: The proxy to be cast.
///   - type: The proxy type to cast to.
///   - facet: The optional name of the desired facet.
///
/// - Returns: A proxy with the requested type.
public func uncheckedCast(prx: Ice.ObjectPrx, type: doPrx.Protocol, facet: Swift.String? = nil) -> doPrx {
    return doPrxI.uncheckedCast(prx: prx, facet: facet) as doPrxI
}

/// Returns the Slice type id of the interface associated with this proxy type.
///
/// - Parameter type:  The proxy type to retrieve the type id.
///
/// - Returns: The type id of the interface associated with this proxy type.
public func ice_staticId(_ type: doPrx.Protocol) -> Swift.String {
    return doTraits.staticId
}

/// Extension to `Ice.InputStream` class to support reading proxies of type
/// `doPrx`.
public extension Ice.InputStream {
    /// Extracts a proxy from the stream. The stream must have been initialized with a communicator.
    ///
    /// - Parameter type: The type of the proxy to be extracted.
    ///
    /// - Returns: The extracted proxy.
    func read(_ type: doPrx.Protocol) throws -> doPrx? {
        return try read() as doPrxI?
    }
    /// Extracts a proxy from the stream. The stream must have been initialized with a communicator.
    ///
    /// - Parameter tag:  The numeric tag associated with the value.
    /// - Parameter type: The type of the proxy to be extracted.
    ///
    /// - Returns: The extracted proxy.
    func read(tag: Swift.Int32, type: doPrx.Protocol) throws -> doPrx? {
        return try read(tag: tag) as doPrxI?
    }
}

public extension doPrx {
    func `public`(context: Ice.Context? = nil) async throws -> Swift.Void {
        return try await _impl._invoke(operation: "public",
                                       mode: .normal,
                                       context: context)
    }

    func goto(`if` iceP_if: `continue`, d iceP_d: `guard`, `private` iceP_private: `switch`?, mutable iceP_mutable: doPrx?, foo iceP_foo: breakPrx?, not iceP_not: `switch`?, or iceP_or: Swift.Int64, context: Ice.Context? = nil) async throws -> `guard` {
        return try await _impl._invoke(operation: "goto",
                                       mode: .normal,
                                       write: { ostr in
                                           ostr.write(iceP_if)
                                           ostr.write(iceP_d)
                                           ostr.write(iceP_private)
                                           ostr.write(iceP_mutable)
                                           ostr.write(iceP_foo)
                                           ostr.write(iceP_not)
                                           ostr.write(iceP_or)
                                           ostr.writePendingValues()
                                       },
                                       read: { istr in
                                           let iceP_returnValue: `guard` = try istr.read()
                                           return iceP_returnValue
                                       },
                                       userException:{ ex in
                                           do  {
                                               throw ex
                                           } catch let error as `as` {
                                               throw error
                                           } catch let error as `return` {
                                               throw error
                                           } catch is Ice.UserException {}
                                       },
                                       context: context)
    }
}

public typealias `fileprivate` = [`guard`]

/// Helper class to read and write `fileprivate` sequence values from
/// `Ice.InputStream` and `Ice.OutputStream`.
public struct fileprivateHelper {
    /// Read a `fileprivate` sequence from the stream.
    ///
    /// - Parameter istr: The stream to read from.
    ///
    /// - Returns: The sequence read from the stream.
    public static func read(from istr: Ice.InputStream) throws -> `fileprivate` {
        let sz = try istr.readAndCheckSeqSize(minSize: 4)
        var v = `fileprivate`()
        v.reserveCapacity(sz)
        for _ in 0 ..< sz {
            let j: `guard` = try istr.read()
            v.append(j)
        }
        return v
    }

    /// Read an optional `fileprivate?` sequence from the stream.
    ///
    /// - Parameter istr: The stream to read from.
    /// - Parameter tag: The numeric tag associated with the value.
    ///
    /// - Returns: The sequence read from the stream.
    public static func read(from istr: Ice.InputStream, tag: Swift.Int32) throws -> `fileprivate`? {
        guard try istr.readOptional(tag: tag, expectedFormat: .VSize) else {
            return nil
        }
        try istr.skipSize()
        return try read(from: istr)
    }

    /// Write a `fileprivate` sequence to the stream.
    ///
    /// - Parameter ostr: The stream to write to.
    /// - Parameter v: The sequence value to write to the stream.
    public static func write(to ostr: Ice.OutputStream, value v: `fileprivate`) {
        ostr.write(size: v.count)
        for item in v {
            ostr.write(item)
        }
    }

    /// Write an optional `fileprivate?` sequence to the stream.
    ///
    /// - Parameters:
    ///   - ostr: The stream to write to.
    ///   - tag: The numeric tag associated with the value.
    ///   - v: The sequence value to write to the stream.
    public static func write(to ostr: Ice.OutputStream,  tag: Swift.Int32, value v: `fileprivate`?) {
        guard let val = v else {
            return
        }
        if ostr.writeOptionalVSize(tag: tag, len: val.count, elemSize: 4) {
            write(to: ostr, value: val)
        }
    }
}

public typealias `for` = [Swift.String: `guard`]

/// Helper class to read and write `for` dictionary values from
/// `Ice.InputStream` and `Ice.OutputStream`.
public struct forHelper {
    /// Read a `for` dictionary from the stream.
    ///
    /// - Parameter istr: The stream to read from.
    ///
    /// - Returns: The dictionary read from the stream.
    public static func read(from istr: Ice.InputStream) throws -> `for` {
        let sz = try Swift.Int(istr.readSize())
        var v = `for`()
        for _ in 0 ..< sz {
            let key: Swift.String = try istr.read()
            let value: `guard` = try istr.read()
            v[key] = value
        }
        return v
    }

    /// Read an optional `for?` dictionary from the stream.
    ///
    /// - Parameter istr: The stream to read from.
    /// - Parameter tag: The numeric tag associated with the value.
    ///
    /// - Returns: The dictionary read from the stream.
    public static func read(from istr: Ice.InputStream, tag: Swift.Int32) throws -> `for`? {
        guard try istr.readOptional(tag: tag, expectedFormat: .FSize) else {
            return nil
        }
        try istr.skip(4)
        return try read(from: istr)
    }

    /// Write a `for` dictionary to the stream.
    ///
    /// - Parameter ostr: The stream to write to.
    /// - Parameter v: The dictionary value to write to the stream.
    public static func write(to ostr: Ice.OutputStream, value v: `for`) {
        ostr.write(size: v.count)
        for (key, value) in v {
            ostr.write(key)
            ostr.write(value)
        }
    }

    /// Write an optional `for?` dictionary to the stream.
    ///
    /// - Parameters:
    ///   - ostr: The stream to write to.
    ///   - tag: The numeric tag associated with the value.
    ///   - v: The dictionary value to write to the stream.
    public static func write(to ostr: Ice.OutputStream, tag: Swift.Int32, value v: `for`?) {
        guard let val = v else {
            return
        }
        if ostr.writeOptional(tag: tag, format: .FSize) {
            let pos = ostr.startSize()
            write(to: ostr, value: val)
            ostr.endSize(position: pos)
        }
    }
}
public let `typealias`: Swift.Int32 = 0



/// Dispatcher for `break` servants.
public struct breakDisp: Ice.Dispatcher {
    public let servant: `break`
    private static let defaultObject = Ice.ObjectI<breakTraits>()

    public init(_ servant: `break`) {
        self.servant = servant
    }

    public func dispatch(_ request: Ice.IncomingRequest) async throws -> Ice.OutgoingResponse {
        switch request.current.operation {
        case "case":
            try await servant._iceD_case(request)
        case "ice_id":
            try await (servant as? Ice.Object ?? breakDisp.defaultObject)._iceD_ice_id(request)
        case "ice_ids":
            try await (servant as? Ice.Object ?? breakDisp.defaultObject)._iceD_ice_ids(request)
        case "ice_isA":
            try await (servant as? Ice.Object ?? breakDisp.defaultObject)._iceD_ice_isA(request)
        case "ice_ping":
            try await (servant as? Ice.Object ?? breakDisp.defaultObject)._iceD_ice_ping(request)
        default:
            throw Ice.OperationNotExistException()
        }
    }
}

public protocol `break` {
    func `case`(`class`: Swift.Int32, current: Ice.Current) async throws -> Swift.Int32
}


/// Dispatcher for `do` servants.
public struct doDisp: Ice.Dispatcher {
    public let servant: `do`
    private static let defaultObject = Ice.ObjectI<doTraits>()

    public init(_ servant: `do`) {
        self.servant = servant
    }

    public func dispatch(_ request: Ice.IncomingRequest) async throws -> Ice.OutgoingResponse {
        switch request.current.operation {
        case "case":
            try await servant._iceD_case(request)
        case "public":
            try await servant._iceD_public(request)
        case "goto":
            try await servant._iceD_goto(request)
        case "ice_id":
            try await (servant as? Ice.Object ?? doDisp.defaultObject)._iceD_ice_id(request)
        case "ice_ids":
            try await (servant as? Ice.Object ?? doDisp.defaultObject)._iceD_ice_ids(request)
        case "ice_isA":
            try await (servant as? Ice.Object ?? doDisp.defaultObject)._iceD_ice_isA(request)
        case "ice_ping":
            try await (servant as? Ice.Object ?? doDisp.defaultObject)._iceD_ice_ping(request)
        default:
            throw Ice.OperationNotExistException()
        }
    }
}

public protocol `do`: `break` {
    func `public`(current: Ice.Current) async throws

    func goto(`if`: `continue`, d: `guard`, `private`: `switch`?, mutable: doPrx?, foo: breakPrx?, not: `switch`?, or: Swift.Int64, current: Ice.Current) async throws -> `guard`
}

extension `break` {
    public func _iceD_case(_ request: Ice.IncomingRequest) async throws -> Ice.OutgoingResponse {
        
        try request.current.checkNonIdempotent()
        let istr = request.inputStream
        _ = try istr.startEncapsulation()
        let iceP_class: Swift.Int32 = try istr.read()
        let result = try await self.`case`(class: iceP_class, current: request.current)
        return request.current.makeOutgoingResponse(result, formatType: nil) { ostr, value in 
            let iceP_try = value
            ostr.write(iceP_try)
        }
    }
}

extension `do` {
    public func _iceD_public(_ request: Ice.IncomingRequest) async throws -> Ice.OutgoingResponse {
        
        try request.current.checkNonIdempotent()
        _ = try request.inputStream.skipEmptyEncapsulation()
        try await self.`public`(current: request.current)
        return request.current.makeEmptyOutgoingResponse()
    }

    public func _iceD_goto(_ request: Ice.IncomingRequest) async throws -> Ice.OutgoingResponse {
        
        try request.current.checkNonIdempotent()
        let istr = request.inputStream
        _ = try istr.startEncapsulation()
        let iceP_if: `continue` = try istr.read()
        let iceP_d: `guard` = try istr.read()
        var iceP_private: `switch`?
        try istr.read(`switch`.self) { iceP_private = $0 }
        let iceP_mutable: doPrx? = try istr.read(doPrx.self)
        let iceP_foo: breakPrx? = try istr.read(breakPrx.self)
        var iceP_not: `switch`?
        try istr.read(`switch`.self) { iceP_not = $0 }
        let iceP_or: Swift.Int64 = try istr.read()
        try istr.readPendingValues()
        let result = try await self.goto(if: iceP_if, d: iceP_d, private: iceP_private, mutable: iceP_mutable, foo: iceP_foo, not: iceP_not, or: iceP_or, current: request.current)
        return request.current.makeOutgoingResponse(result, formatType: nil) { ostr, value in 
            let iceP_returnValue = value
            ostr.write(iceP_returnValue)
        }
    }
}
