// Copyright (c) ZeroC, Inc.

// slice2java version 3.8.0-alpha.0
// <auto-generated>Generated from Slice file 'TestAMD.ice'.</auto-generated>

package Test;

public final class S implements java.lang.Cloneable, java.io.Serializable {
    public int i;

    /**
     * Constructs a {@code S}.
     */
    public S() {
    }

    /**
     * Constructs a {@code S} with values for all fields not marked optional in the Slice definition for {@code ::Test::S}.
     */
    public S(int i) {
        this.i = i;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean equals(java.lang.Object rhs) {
        if (this == rhs) {
            return true;
        }
        S r = null;
        if (rhs instanceof S) {
            r = (S)rhs;
        }

        if (r != null) {
            if (this.i != r.i) {
                return false;
            }

            return true;
        }

        return false;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public int hashCode() {
        int h_ = 5381;
        h_ = com.zeroc.Ice.HashUtil.hashAdd(h_, "::Test::S");
        h_ = com.zeroc.Ice.HashUtil.hashAdd(h_, i);
        return h_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public S clone() {
        S c = null;
        try {
            c = (S) super.clone();
        } catch (java.lang.CloneNotSupportedException ex) {
            assert false; // impossible
        }
        return c;
    }

    /**
     * Marshals this object's fields into an output stream.
     *
     * @param ostr the output stream
     */
    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr) {
        ostr.writeInt(this.i);
    }

    /**
     * Unmarshals and sets this object's fields from an input stream.
     *
     * @param istr the input stream
     */
    public void ice_readMembers(com.zeroc.Ice.InputStream istr) {
        this.i = istr.readInt();
    }

    /**
     * Marshals a {@code S} into an output stream.
     *
     * @param ostr the output stream
     * @param v the {@code S} to marshal; can be null
     */
    static public void ice_write(com.zeroc.Ice.OutputStream ostr, S v) {
        if (v == null) {
            _nullMarshalValue.ice_writeMembers(ostr);
        } else {
            v.ice_writeMembers(ostr);
        }
    }

    /**
     * Unmarshals a {@code S} from an input stream.
     *
     * @param istr the input stream 
     * @return the unmarshaled {@code S}
     */
    static public S ice_read(com.zeroc.Ice.InputStream istr) {
        S v = new S();
        v.ice_readMembers(istr);
        return v;
    }

    /**
     * Marshals an optional {@code S} into an output stream.
     *
     * @param ostr the output stream
     * @param tag the tag
     * @param v the value to marshal
     */
    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<S> v) {
        if (v != null && v.isPresent()) {
            ice_write(ostr, tag, v.get());
        }
    }

    /**
     * Marshals an optional {@code S} into an output stream.
     *
     * @param ostr the output stream
     * @param tag the tag
     * @param v the value to marshal
     */
    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, S v) {
        if (ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize)) {
            ostr.writeSize(4);
            ice_write(ostr, v);
        }
    }

    /**
     * Unmarshals an optional {@code S} from an input stream.
     *
     * @param istr the input stream
     * @param tag the tag
     * @return the unmarshaled value
     */
    static public java.util.Optional<S> ice_read(com.zeroc.Ice.InputStream istr, int tag) {
        if (istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize)) {
            istr.skipSize();
            return java.util.Optional.of(S.ice_read(istr));
        } else {
            return java.util.Optional.empty();
        }
    }

    private static final S _nullMarshalValue = new S();

    private static final long serialVersionUID = -5205422450358775315L;
}
