//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.8.0-alpha.0
//
// <auto-generated>
//
// Generated from file 'EndpointTypes.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#nullable enable

[assembly:Ice.Slice("EndpointTypes.ice")]

#pragma warning disable CS1591 // Missing XML Comment
#pragma warning disable CS1573 // Parameter has no matching param tag in the XML comment
#pragma warning disable CS0612 // Type or member is obsolete
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS0619 // Type or member is obsolete

namespace Ice
{
    public abstract class TCPEndpointType
    {
        public const short value = 1;
    }

    public abstract class SSLEndpointType
    {
        public const short value = 2;
    }

    public abstract class UDPEndpointType
    {
        public const short value = 3;
    }

    public abstract class WSEndpointType
    {
        public const short value = 4;
    }

    public abstract class WSSEndpointType
    {
        public const short value = 5;
    }

    public abstract class BTEndpointType
    {
        public const short value = 6;
    }

    public abstract class BTSEndpointType
    {
        public const short value = 7;
    }

    public abstract class iAPEndpointType
    {
        public const short value = 8;
    }

    public abstract class iAPSEndpointType
    {
        public const short value = 9;
    }
}
