// Copyright (c) ZeroC, Inc.

// slice2java version 3.8.0-alpha.0
// <auto-generated>Generated from Slice file 'Contract.ice'.</auto-generated>

package DataStormContract;

/**
 * The PublisherSession servant is hosted by the publisher node and is accessed by the subscriber node.
 */
@com.zeroc.Ice.SliceTypeId(value = "::DataStormContract::PublisherSession")
public interface PublisherSession extends Session {
    /**
     * Gets the type ID of the associated Slice interface.
     *
     * @return the string "::DataStormContract::PublisherSession"
     */
    static java.lang.String ice_staticId() {
        return "::DataStormContract::PublisherSession";
    }

    /**
     * Dispatches an incoming request to one of the methods of this generated interface, based on the operation name carried by the request.
     *
     * @param request the incoming request
     * @return the outgoing response
     * @throws com.zeroc.Ice.UserException if a {@code UserException} is thrown, Ice will marshal it as the response payload.
     */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutgoingResponse> dispatch(com.zeroc.Ice.IncomingRequest request)
        throws com.zeroc.Ice.UserException {
        return switch (request.current.operation) {
            case "announceTopics" -> Session._iceD_announceTopics(this, request);
            case "attachTopic" -> Session._iceD_attachTopic(this, request);
            case "detachTopic" -> Session._iceD_detachTopic(this, request);
            case "attachTags" -> Session._iceD_attachTags(this, request);
            case "detachTags" -> Session._iceD_detachTags(this, request);
            case "announceElements" -> Session._iceD_announceElements(this, request);
            case "attachElements" -> Session._iceD_attachElements(this, request);
            case "attachElementsAck" -> Session._iceD_attachElementsAck(this, request);
            case "detachElements" -> Session._iceD_detachElements(this, request);
            case "initSamples" -> Session._iceD_initSamples(this, request);
            case "disconnected" -> Session._iceD_disconnected(this, request);
            case "ice_id" -> com.zeroc.Ice.Object._iceD_ice_id(this, request);
            case "ice_ids" -> com.zeroc.Ice.Object._iceD_ice_ids(this, request);
            case "ice_isA" -> com.zeroc.Ice.Object._iceD_ice_isA(this, request);
            case "ice_ping" -> com.zeroc.Ice.Object._iceD_ice_ping(this, request);
            default -> throw new com.zeroc.Ice.OperationNotExistException();
        };
    }
}
