// Copyright (c) ZeroC, Inc.

// slice2java version 3.8.0-alpha.0
// <auto-generated>Generated from Slice file 'Exception.ice'.</auto-generated>

package com.zeroc.IceGrid;

/**
 * The exception that is thrown when IceGrid cannot reach a registry.
 **/
@com.zeroc.Ice.SliceTypeId(value = "::IceGrid::RegistryUnreachableException")
public class RegistryUnreachableException extends com.zeroc.Ice.UserException
{
    public RegistryUnreachableException()
    {
        this.name = "";
        this.reason = "";
    }

    public RegistryUnreachableException(String name, String reason)
    {
        this.name = name;
        this.reason = reason;
    }

    public String ice_id()
    {
        return "::IceGrid::RegistryUnreachableException";
    }

    /**
     * The name of the registry that is not reachable.
     **/
    public String name;

    /**
     * The reason why the registry couldn't be reached.
     **/
    public String reason;

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::IceGrid::RegistryUnreachableException", -1, true);
        ostr_.writeString(name);
        ostr_.writeString(reason);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        name = istr_.readString();
        reason = istr_.readString();
        istr_.endSlice();
    }

    /** @hidden */
    private static final long serialVersionUID = 6094429676385867006L;
}
