// Copyright (c) ZeroC, Inc.

// slice2java version 3.8.0-alpha.0
// <auto-generated>Generated from Slice file 'Test.ice'.</auto-generated>

package test.Ice.objects.Test;

@com.zeroc.Ice.SliceTypeId(value = "::Test::Compact")
@com.zeroc.Ice.CompactSliceTypeId(value = 1)
public class Compact extends com.zeroc.Ice.Value {
    public Compact clone() {
        return (Compact) super.clone();
    }

    /**
     * Gets the type ID of the associated Slice interface.
     *
     * @return the string "::Test::Compact"
     */
    public static java.lang.String ice_staticId() {
        return "::Test::Compact";
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public java.lang.String ice_id() {
        return ice_staticId();
    }

    /**
     * {@inheritDoc}
     * @hidden
     */
    @Override
    protected void _iceWriteImpl(com.zeroc.Ice.OutputStream ostr_) {
        ostr_.startSlice(ice_staticId(), 1, true);
        ostr_.endSlice();
    }

    /**
     * {@inheritDoc}
     * @hidden
     */
    @Override
    protected void _iceReadImpl(com.zeroc.Ice.InputStream istr_) {
        istr_.startSlice();
        istr_.endSlice();
    }

    private static final long serialVersionUID = -2849577689998930812L;
}
